

KernelThreadPath = $(KernelPath)/Thread
KernelThreadSrc = $(KernelThreadPath)/Thread.cc \
	$(KernelThreadPath)/CreateThread.cc \
	$(KernelThreadPath)/TerminateThread.cc \
	$(KernelThreadPath)/SCThread.cc

