

KernelProcessPath = $(KernelPath)/Process
KernelProcessSrc = $(KernelProcessPath)/Process.cc \
	$(KernelProcessPath)/CreateProcess.cc \
	$(KernelProcessPath)/SCFree.cc \
	$(KernelProcessPath)/SCMalloc.cc

