// File: SystemCall.h

/*
 Copyright (c) 1998-1999 Murphy Cheng-Che Chen. All Rights Reserved.

 This software is provided "AS IS," without a warranty of any kind. ALL
 EXPRESS OR IMPLIED CONDITIONS, REPRESENTATIONS AND WARRANTIES, INCLUDING
 ANY IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
 OR NON-INFRINGEMENT, ARE HEREBY EXCLUDED. MURPHY CHENG-CHE CHEN AND HIS
 LICENSORS SHALL NOT BE LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A
 RESULT OF USING, MODIFYING OR DISTRIBUTING THE SOFTWARE OR ITS DERIVATIVES.
 IN NO EVENT WILL MURPHY CHENG-CHE CHEN OR HIS LICENSORS BE LIABLE FOR ANY
 LOST REVENUE, PROFIT OR DATA, OR FOR DIRECT, INDIRECT, SPECIAL,
 CONSEQUENTIAL, INCIDENTAL OR PUNITIVE DAMAGES, HOWEVER CAUSED AND REGARDLESS
 OF THE THEORY OF LIABILITY, ARISING OUT OF THE USE OF OR INABILITY TO USE
 SOFTWARE, EVEN IF MURPHY CHENG-CHE CHEN HAS BEEN ADVISED OF THE POSSIBILITY
 OF SUCH DAMAGES.

 murphy@hpc.ee.ntu.edu.tw
 http://hpc.ee.ntu.edu.tw/~murphy/
*/

/*
1999/02/02: Created by Murphy Che-Cher Chen
	SC_SERIAL_PUTCHAR
	SC_SERIAL_PUTS
1999/02/13: Murphy
	SC_CREATE_SEMAPHORE
	SC_OPEN_SEMAPHORE
	SC_WAIT_SEMAPHORE
	SC_SIGNAL_SEMAPHORE
1999/03/01: Murphy
	SC_CREATE_MESSAGEQUEUE
	SC_OPEN_MESSAGEQUEUE
	SC_SEND_MESSAGE
	SC_GET_MESSAGE
*/

#ifndef __EKERNEL_SYSTEM_CALL_H_
#define __EKERNEL_SYSTEM_CALL_H_


#define MAX_NO_SYSTEM_CALL	0x1000

#define SC_CREATE_THREAD	0x0000
#define SC_TERMINATE_THREAD	0x0001

#define SC_CREATE_SEMAPHORE	0x0010
#define SC_OPEN_SEMAPHORE	0x0011
#define SC_WAIT_SEMAPHORE	0x0012
#define SC_SIGNAL_SEMAPHORE	0x0013

#define	SC_CREATE_MESSAGEQUEUE	0x0020
#define	SC_OPEN_MESSAGEQUEUE	0x0021
#define	SC_SEND_MESSAGE		0x0022
#define	SC_GET_MESSAGE		0x0023


#define SC_SERIAL_PUTCHAR	0x009E
#define SC_SERIAL_PUTS		0x009F


#endif
