
KernelMessagePath = $(KernelPath)/Message
KernelMessageSrc = $(KernelMessagePath)/MessageQueue.cc \
	$(KernelMessagePath)/CreateMessageQueue.cc \
	$(KernelMessagePath)/OpenMessageQueue.cc \
	$(KernelMessagePath)/SCMessageQueue.cc