
KernelSemaphorePath = $(KernelPath)/Semaphore

KernelSemaphoreSrc = $(KernelSemaphorePath)/Semaphore.cc \
	$(KernelSemaphorePath)/CreateSemaphore.cc \
	$(KernelSemaphorePath)/OpenSemaphore.cc \
	$(KernelSemaphorePath)/SCSemaphore.cc

