
KernelPath = Kernel

include Kernel/Event/Makefile
include Kernel/Interrupt/Makefile
include Kernel/Message/Makefile
include Kernel/Mutex/Makefile
include Kernel/Process/Makefile
include Kernel/Scheduler/Makefile
include Kernel/Semaphore/Makefile
include Kernel/SystemCall/Makefile
include Kernel/Thread/Makefile

KernelSrc = $(KernelEventSrc) $(KernelInterruptSrc) $(KernelMessageSrc) \
	$(KernelMutexSrc) $(KernelProcessSrc) $(KernelSchedulerSrc) \
	$(KernelSemaphoreSrc) $(KernelSystemCallSrc) $(KernelThreadSrc)
