
HardwarePentiumPath = Hardware/Pentium
HardwarePentiumSrc = $(HardwarePentiumPath)/cpuid.cc \
	$(HardwarePentiumPath)/Trap.cc \
	$(HardwarePentiumPath)/GDT.cc \
	$(HardwarePentiumPath)/Intel8259InterruptController.cc \
	$(HardwarePentiumPath)/PageDirectory.cc \
	$(HardwarePentiumPath)/PageTable.cc \
	$(HardwarePentiumPath)/PentiumMMU.cc \
	$(HardwarePentiumPath)/PentiumProcessor.cc \
	$(HardwarePentiumPath)/TSS.cc \
	$(HardwarePentiumPath)/IDT.cc

HardwarePentiumAsmSrc = $(HardwarePentiumPath)/trap_tab.asm \
	$(HardwarePentiumPath)/context_switch.asm \
	$(HardwarePentiumPath)/system_call_stub.asm \
	$(HardwarePentiumPath)/trigger_timer_interrupt.asm
