
InitializePentiumPath = Initialize/Pentium
InitializePentiumSrc = $(InitializePentiumPath)/multi_boot_main.cc \
	$(InitializePentiumPath)/multi_boot_find.cc \
	$(InitializePentiumPath)/multi_boot_dump.cc \
	$(InitializePentiumPath)/PentiumMain.cc

InitializePentiumAsmSrc = $(InitializePentiumPath)/entry.asm
