
LibCPath = LibC

#include LibC/malloc/Makefile
include LibC/stdio/Makefile
#include LibC/string/Makefile
#include LibC/assert/Makefile

LibCSrc =  $(LibCMallocSrc) $(LibCStdioSrc) $(LibCStringSrc) \
	$(LibCAssertSrc) # LibC/libgcc2.cc

LibCAsmSrc = $(LibCStringAsmSrc)
